name: generate_html_pdf
on:
  push:
    branches:
      - master
    paths:
      - src/**

jobs:
  generate-html-and-pdf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Generate html and pdf file
        uses: docker://pandoc/core:2.9
        with:
          args: --standalone -c src/style.css -o resume-jordi-toda.html src/resume.md
      - name: Generate pdf file
        run: |
          sudo apt-get install xvfb libfontconfig wkhtmltopdf
          xvfb-run wkhtmltopdf --margin-left 12 --margin-top 12 --margin-right 12 --margin-bottom 12 resume-jordi-toda.html resume-jordi-toda.pdf
      - name: Commit changes
        run: |
          git config --local user.email "todajordi97@gmail.com"
          git config --local user.name "Jordi Toda"
          git add resume-jordi-toda.html resume-jordi-toda.pdf
          git commit -m "chore: Generate html and pdf files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}