name: generate_html_pdf
on:
  push:
    branches: [ master ]

jobs:
  generate-html-and-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate html file
        uses: docker://pandoc/core:2.9
        with:
          args: --standalone -c src/style.css -o index.html src/resume.md

      - name: Generate pdf file
        run: |
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          sudo apt-get update
          sudo apt-get install xvfb libfontconfig wkhtmltopdf
          xvfb-run wkhtmltopdf --enable-local-file-access --margin-left 14 --margin-right 14 --margin-top 12 --margin-bottom 12 index.html resume.pdf

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html resume.pdf
          git commit -m "[Action] Generate html and pdf files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: ${{ github.head_ref }}